const sampleListings = [
  {
    title: "Cozy Beachfront Cottage",
    description: "Escape to this charming beachfront cottage for a relaxing getaway. Enjoy stunning ocean views and easy access to the beach.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1552733407-5d5c46c3bb3b?auto=format&fit=crop&w=800&q=60" },
    price: 1500, location: "Malibu", country: "United States",
  },
  {
    title: "Modern Loft in Downtown",
    description: "Stay in the heart of the city in this stylish loft apartment. Perfect for urban explorers!",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=800&q=60" },
    price: 1200, location: "New York City", country: "United States",
  },
  {
    title: "Mountain Retreat",
    description: "Unplug and unwind in this peaceful mountain cabin. Surrounded by nature, it's a perfect place to recharge.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=800&q=60" },
    price: 1000, location: "Aspen", country: "United States",
  },
  {
    title: "Historic Villa in Tuscany",
    description: "Experience the charm of Tuscany in this beautifully restored villa. Explore the rolling hills and vineyards.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=800&q=60" },
    price: 2500, location: "Florence", country: "Italy",
  },
  {
    title: "Secluded Treehouse Getaway",
    description: "Live among the treetops in this unique treehouse retreat. A true nature lover's paradise.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&w=800&q=60" },
    price: 800, location: "Portland", country: "United States",
  },
  {
    title: "Beachfront Paradise",
    description: "Step out of your door onto the sandy beach. This beachfront condo offers the ultimate relaxation.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?auto=format&fit=crop&w=800&q=60" },
    price: 2000, location: "Cancun", country: "Mexico",
  },
  {
    title: "Rustic Cabin by the Lake",
    description: "Spend your days fishing and kayaking on the serene lake. This cozy cabin is perfect for outdoor enthusiasts.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=800&q=60" },
    price: 900, location: "Lake Tahoe", country: "United States",
  },
  {
    title: "Luxury Penthouse with City Views",
    description: "Indulge in luxury living with panoramic city views from this stunning penthouse apartment.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1622396481328-9b1b78cdd9fd?auto=format&fit=crop&w=800&q=60" },
    price: 3500, location: "Los Angeles", country: "United States",
  },
  {
    title: "Ski-In/Ski-Out Chalet",
    description: "Hit the slopes right from your doorstep in this ski-in/ski-out chalet in the Swiss Alps.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1502784444187-359ac186c5bb?auto=format&fit=crop&w=800&q=60" },
    price: 3000, location: "Verbier", country: "Switzerland",
  },
  {
    title: "Safari Lodge in the Serengeti",
    description: "Experience the thrill of the wild in a comfortable safari lodge. Witness the Great Migration up close.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1493246507139-91e8fad9978e?auto=format&fit=crop&w=800&q=60" },
    price: 4000, location: "Serengeti National Park", country: "Tanzania",
  },
  {
    title: "Historic Canal House",
    description: "Stay in a piece of history in this beautifully preserved canal house in Amsterdam's iconic district.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=800&q=60" },
    price: 1800, location: "Amsterdam", country: "Netherlands",
  },
  {
    title: "Private Island Retreat",
    description: "Have an entire island to yourself for a truly exclusive and unforgettable vacation experience.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1618140052121-39fc6db33972?auto=format&fit=crop&w=800&q=60" },
    price: 10000, location: "Fiji", country: "Fiji",
  },
  {
    title: "Charming Cottage in the Cotswolds",
    description: "Escape to the picturesque Cotswolds in this quaint and charming cottage with a thatched roof.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1602088113235-229c19758e9f?auto=format&fit=crop&w=800&q=60" },
    price: 1200, location: "Cotswolds", country: "United Kingdom",
  },
  {
    title: "Historic Brownstone in Boston",
    description: "Step back in time in this elegant historic brownstone located in the heart of Boston.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1533619239233-6280475a633a?auto=format&fit=crop&w=800&q=60" },
    price: 2200, location: "Boston", country: "United States",
  },
  {
    title: "Beachfront Bungalow in Bali",
    description: "Relax on the sandy shores of Bali in this beautiful beachfront bungalow with a private pool.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1602391833977-358a52198938?auto=format&fit=crop&w=800&q=60" },
    price: 1800, location: "Bali", country: "Indonesia",
  },
  {
    title: "Mountain View Cabin in Banff",
    description: "Enjoy breathtaking mountain views from this cozy cabin in the Canadian Rockies.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1521401830884-6c03c1c87ebb?auto=format&fit=crop&w=800&q=60" },
    price: 1500, location: "Banff", country: "Canada",
  },
  {
    title: "Art Deco Apartment in Miami",
    description: "Step into the glamour of the 1920s in this stylish Art Deco apartment in South Beach.",
    image: { filename: "listingimage", url: "https://plus.unsplash.com/premium_photo-1670963964797-942df1804579?auto=format&fit=crop&w=800&q=60" },
    price: 1600, location: "Miami", country: "United States",
  },
  {
    title: "Tropical Villa in Phuket",
    description: "Escape to a tropical paradise in this luxurious villa with a private infinity pool in Phuket.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1470165301023-58dab8118cc9?auto=format&fit=crop&w=800&q=60" },
    price: 3000, location: "Phuket", country: "Thailand",
  },
  {
    title: "Historic Castle in Scotland",
    description: "Live like royalty in this historic castle in the Scottish Highlands. Explore the rugged beauty of the area.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1585543805890-6051f7829f98?auto=format&fit=crop&w=800&q=60" },
    price: 4000, location: "Scottish Highlands", country: "United Kingdom",
  },
  {
    title: "Desert Oasis in Dubai",
    description: "Experience luxury in the middle of the desert in this opulent oasis in Dubai with a private pool.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1518684079-3c830dcef090?auto=format&fit=crop&w=800&q=60" },
    price: 5000, location: "Dubai", country: "United Arab Emirates",
  },
  {
    title: "Rustic Log Cabin in Montana",
    description: "Unplug and unwind in this cozy log cabin surrounded by the natural beauty of Montana.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1586375300773-8384e3e4916f?auto=format&fit=crop&w=800&q=60" },
    price: 1100, location: "Montana", country: "United States",
  },
  {
    title: "Beachfront Villa in Greece",
    description: "Enjoy the crystal-clear waters of the Mediterranean in this beautiful beachfront villa on a Greek island.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1602343168117-bb8ffe3e2e9f?auto=format&fit=crop&w=800&q=60" },
    price: 2500, location: "Mykonos", country: "Greece",
  },
  {
    title: "Eco-Friendly Treehouse Retreat",
    description: "Stay in an eco-friendly treehouse nestled in the forest. It's the perfect escape for nature lovers.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1488462237308-ecaa28b729d7?auto=format&fit=crop&w=800&q=60" },
    price: 750, location: "Costa Rica", country: "Costa Rica",
  },
  {
    title: "Historic Cottage in Charleston",
    description: "Experience the charm of historic Charleston in this beautifully restored cottage with a private garden.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1587381420270-3e1a5b9e6904?auto=format&fit=crop&w=800&q=60" },
    price: 1600, location: "Charleston", country: "United States",
  },
  {
    title: "Modern Apartment in Tokyo",
    description: "Explore the vibrant city of Tokyo from this modern and centrally located apartment.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1480796927426-f609979314bd?auto=format&fit=crop&w=800&q=60" },
    price: 2000, location: "Tokyo", country: "Japan",
  },
  {
    title: "Lakefront Cabin in New Hampshire",
    description: "Spend your days by the lake in this cozy cabin in the scenic White Mountains of New Hampshire.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1578645510447-e20b4311e3ce?auto=format&fit=crop&w=800&q=60" },
    price: 1200, location: "New Hampshire", country: "United States",
  },
  {
    title: "Luxury Villa in the Maldives",
    description: "Indulge in luxury in this overwater villa in the Maldives with stunning views of the Indian Ocean.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=800&q=60" },
    price: 6000, location: "Maldives", country: "Maldives",
  },
  {
    title: "Ski Chalet in Aspen",
    description: "Hit the slopes in style with this luxurious ski chalet in the world-famous Aspen ski resort.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?auto=format&fit=crop&w=800&q=60" },
    price: 4000, location: "Aspen", country: "United States",
  },
  {
    title: "Secluded Beach House in Costa Rica",
    description: "Escape to a secluded beach house on the Pacific coast of Costa Rica. Surf, relax, and unwind.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?auto=format&fit=crop&w=800&q=60" },
    price: 1800, location: "Costa Rica", country: "Costa Rica",
  },
  // --- New listings below ---
  {
    title: "Clifftop Villa in Santorini",
    description: "Wake up to iconic blue-domed views in this stunning clifftop villa perched above the Aegean Sea.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?auto=format&fit=crop&w=800&q=60" },
    price: 3200, location: "Santorini", country: "Greece",
  },
  {
    title: "Vineyard Cottage in Bordeaux",
    description: "Stay surrounded by world-class vineyards in this rustic yet elegant French countryside cottage.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?auto=format&fit=crop&w=800&q=60" },
    price: 1900, location: "Bordeaux", country: "France",
  },
  {
    title: "Ryokan-Style Inn in Kyoto",
    description: "Experience traditional Japanese hospitality in this authentic ryokan with tatami rooms and onsen baths.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1528360983277-13d401cdc186?auto=format&fit=crop&w=800&q=60" },
    price: 2200, location: "Kyoto", country: "Japan",
  },
  {
    title: "Overwater Bungalow in Bora Bora",
    description: "Float above the crystal lagoon in this iconic overwater bungalow in the heart of French Polynesia.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=60" },
    price: 7500, location: "Bora Bora", country: "French Polynesia",
  },
  {
    title: "Countryside Farmhouse in Provence",
    description: "Breathe in the lavender fields and enjoy the slow life at this charming Provençal farmhouse.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1464278533981-50106e6176b1?auto=format&fit=crop&w=800&q=60" },
    price: 1700, location: "Provence", country: "France",
  },
  {
    title: "Glass Igloo in Finnish Lapland",
    description: "Sleep under the Northern Lights in a cozy glass igloo surrounded by snow-covered Arctic wilderness.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1531366936337-7c912a4589a7?auto=format&fit=crop&w=800&q=60" },
    price: 4500, location: "Rovaniemi", country: "Finland",
  },
  {
    title: "Colonial Mansion in Cartagena",
    description: "Step into the vibrant colors and rich history of this beautifully restored colonial mansion.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=800&q=60" },
    price: 2100, location: "Cartagena", country: "Colombia",
  },
  {
    title: "Houseboat on Dal Lake",
    description: "Experience the tranquil beauty of Kashmir from this traditional wooden houseboat on Dal Lake.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=800&q=60" },
    price: 950, location: "Srinagar", country: "India",
  },
  {
    title: "Cliffside Cave Hotel in Cappadocia",
    description: "Explore ancient rock formations and hot air balloon-dotted skies from this unique cave hotel.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1541432901042-2d8bd64b4a9b?auto=format&fit=crop&w=800&q=60" },
    price: 1600, location: "Göreme", country: "Turkey",
  },
  {
    title: "Beachfront Cabana in the Maldives",
    description: "Fall asleep to the sound of waves in this private beachfront cabana with direct lagoon access.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1513519245088-0e12902e5a38?auto=format&fit=crop&w=800&q=60" },
    price: 5500, location: "North Malé Atoll", country: "Maldives",
  },
  {
    title: "Luxury Riad in Marrakech",
    description: "Escape into the heart of Marrakech's medina in this opulently decorated traditional Moroccan riad.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1560185893-a55cbc8c57e8?auto=format&fit=crop&w=800&q=60" },
    price: 2300, location: "Marrakech", country: "Morocco",
  },
  {
    title: "Rainforest Eco-Lodge in Borneo",
    description: "Discover the incredible biodiversity of Borneo from this sustainable eco-lodge in the jungle canopy.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1516026672322-bc52d61a55d5?auto=format&fit=crop&w=800&q=60" },
    price: 1300, location: "Kota Kinabalu", country: "Malaysia",
  },
  {
    title: "Alpine Chalet in the Dolomites",
    description: "Marvel at the jagged pink peaks of the Dolomites from this cozy chalet with a wood-burning fireplace.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1505118380757-91f5f5632de0?auto=format&fit=crop&w=800&q=60" },
    price: 2700, location: "Cortina d'Ampezzo", country: "Italy",
  },
  {
    title: "Seaside Apartment in Barcelona",
    description: "Enjoy Gaudí's city from a breezy seaside apartment just minutes from the beach and the Gothic Quarter.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1539037116277-4db20889f2d4?auto=format&fit=crop&w=800&q=60" },
    price: 1750, location: "Barcelona", country: "Spain",
  },
  {
    title: "Floating Villa in Bangkok",
    description: "Experience Bangkok's iconic waterways from this unique floating villa along the Chao Phraya River.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1508193638397-1c4234db14d8?auto=format&fit=crop&w=800&q=60" },
    price: 1450, location: "Bangkok", country: "Thailand",
  },
  {
    title: "Modernist Beach House in Sydney",
    description: "Soak up Sydney's sunshine in this architect-designed beach house with panoramic Pacific Ocean views.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1523217582562-09d0def993a6?auto=format&fit=crop&w=800&q=60" },
    price: 3100, location: "Bondi Beach", country: "Australia",
  },
  {
    title: "Boutique Hotel Room in Prague",
    description: "Stay in a gorgeously appointed boutique room in Prague's historic Old Town, steps from the Astronomical Clock.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1592906209472-a36b1f3782ef?auto=format&fit=crop&w=800&q=60" },
    price: 980, location: "Prague", country: "Czech Republic",
  },
  {
    title: "Jungle Bungalow in Ubud",
    description: "Reconnect with nature in this peaceful jungle bungalow surrounded by terraced rice paddies in Ubud.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=800&q=60" },
    price: 1050, location: "Ubud", country: "Indonesia",
  },
  {
    title: "Hacienda Estate in Mexico City",
    description: "Stay in a historic hacienda with lush courtyards and colonial architecture in the heart of Mexico City.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1555400038-63f5ba517a47?auto=format&fit=crop&w=800&q=60" },
    price: 2000, location: "Mexico City", country: "Mexico",
  },
  {
    title: "Waterfront Cottage in Cape Town",
    description: "Enjoy spectacular views of Table Mountain from this charming waterfront cottage at the V&A Marina.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1580060839134-75a5edca2e99?auto=format&fit=crop&w=800&q=60" },
    price: 2400, location: "Cape Town", country: "South Africa",
  },
  {
    title: "Lakeside Retreat in Queenstown",
    description: "Adventure-seekers rejoice — this lakeside home puts you minutes from bungee jumping, skiing, and hiking.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1507699622108-4be3abd695ad?auto=format&fit=crop&w=800&q=60" },
    price: 2600, location: "Queenstown", country: "New Zealand",
  },
  {
    title: "Penthouse Suite in Singapore",
    description: "Live the high life in this ultra-modern penthouse with a rooftop infinity pool above the Singapore skyline.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1525625293386-3f8f99389edd?auto=format&fit=crop&w=800&q=60" },
    price: 5800, location: "Singapore", country: "Singapore",
  },
  {
    title: "Farmstay in the Tuscany Hills",
    description: "Wake up to rolling vineyard views, enjoy farm-fresh breakfasts, and explore the Chianti countryside.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1560347876-aeef00ee58a1?auto=format&fit=crop&w=800&q=60" },
    price: 1350, location: "Siena", country: "Italy",
  },
  {
    title: "Desert Camp in Wadi Rum",
    description: "Sleep under a million stars in a luxury Bedouin camp set among the red sand dunes of Wadi Rum.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1509316785289-025f5b846b35?auto=format&fit=crop&w=800&q=60" },
    price: 1700, location: "Wadi Rum", country: "Jordan",
  },
  {
    title: "Cliffside Villa in Amalfi",
    description: "Dangle above the turquoise Tyrrhenian Sea in this breathtaking cliffside villa on the Amalfi Coast.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1533587851505-d119e13fa0d7?auto=format&fit=crop&w=800&q=60" },
    price: 3800, location: "Amalfi", country: "Italy",
  },
  {
    title: "Tented Safari Camp in Kenya",
    description: "Luxury meets wilderness in this award-winning tented camp on the banks of the Mara River.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1516426122078-c23e76319801?auto=format&fit=crop&w=800&q=60" },
    price: 4200, location: "Maasai Mara", country: "Kenya",
  },
  {
    title: "Colourful Townhouse in Notting Hill",
    description: "Stay in one of London's most charming neighbourhoods in this pastel-coloured Georgian townhouse.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1555708982-8645ec9ce3cc?auto=format&fit=crop&w=800&q=60" },
    price: 2900, location: "London", country: "United Kingdom",
  },
  {
    title: "Converted Windmill in the Netherlands",
    description: "Sleep inside a working windmill in the Dutch countryside — a once-in-a-lifetime experience.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1467269204594-9661b134dd2b?auto=format&fit=crop&w=800&q=60" },
    price: 1550, location: "Kinderdijk", country: "Netherlands",
  },
  {
    title: "Heritage Bungalow in Penang",
    description: "Stay in a lovingly restored Peranakan shophouse in Penang's UNESCO-listed heritage zone.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1549298240-0d8e60513026?auto=format&fit=crop&w=800&q=60" },
    price: 870, location: "George Town", country: "Malaysia",
  },
  {
    title: "Ski Lodge in Whistler",
    description: "Ski-in, ski-out access to one of North America's best resorts from this cozy mountain lodge.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1551524559-8af4e6624178?auto=format&fit=crop&w=800&q=60" },
    price: 3600, location: "Whistler", country: "Canada",
  },
  {
    title: "Riverside Cottage in Bruges",
    description: "Glide along medieval canals and cobblestone streets from this romantic riverside cottage in Bruges.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1491555103944-7c647fd857e6?auto=format&fit=crop&w=800&q=60" },
    price: 1400, location: "Bruges", country: "Belgium",
  },
  {
    title: "Luxury Apartment in Vienna",
    description: "Reside like an aristocrat in this high-ceilinged Viennese apartment steps from the Opera House.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1516550893923-42d28e5677af?auto=format&fit=crop&w=800&q=60" },
    price: 2050, location: "Vienna", country: "Austria",
  },
  {
    title: "Floating Cabin in Sweden",
    description: "Drift gently on a glassy Swedish lake in this architect-designed floating cabin with a wood-fired sauna.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1470770841072-f978cf4d019e?auto=format&fit=crop&w=800&q=60" },
    price: 1650, location: "Stockholm Archipelago", country: "Sweden",
  },
  {
    title: "Bohemian Studio in Lisbon",
    description: "Experience Lisbon's fado music, tiled azulejo facades, and sunset views from this artsy bohemian studio.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1555881400-74d7acaacd8b?auto=format&fit=crop&w=800&q=60" },
    price: 920, location: "Lisbon", country: "Portugal",
  },
  {
    title: "Heritage Plantation in Kerala",
    description: "Wake up to mist-covered spice gardens and backwater sounds at this beautifully restored colonial plantation.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?auto=format&fit=crop&w=800&q=60" },
    price: 1100, location: "Munnar", country: "India",
  },
  {
    title: "Beachfront Palapa in Tulum",
    description: "Unwind in an open-air palapa just steps from Tulum's turquoise waters and ancient Maya ruins.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1504701954957-2010ec3bcec1?auto=format&fit=crop&w=800&q=60" },
    price: 1950, location: "Tulum", country: "Mexico",
  },
  {
    title: "Luxury Houseboat in Amsterdam",
    description: "Drift through Amsterdam's famous canal network from this beautifully designed luxury houseboat.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1534430480872-3498386e7856?auto=format&fit=crop&w=800&q=60" },
    price: 2150, location: "Amsterdam", country: "Netherlands",
  },
  {
    title: "Clifftop Retreat in Big Sur",
    description: "Find serenity at this dramatic cliffside hideaway perched above the crashing Pacific surf in Big Sur.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1465146344425-f00d5f5c8f07?auto=format&fit=crop&w=800&q=60" },
    price: 2800, location: "Big Sur", country: "United States",
  },
  {
    title: "Stilt House in the Mekong Delta",
    description: "Experience the rhythms of rural Vietnamese life in a traditional stilt house above the Mekong River.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1528360983277-13d401cdc186?auto=format&fit=crop&w=800&q=60" },
    price: 600, location: "Can Tho", country: "Vietnam",
  },
  {
    title: "Mountaintop Monastery Guesthouse",
    description: "Find inner peace at a centuries-old monastery guesthouse nestled in the Himalayan peaks of Bhutan.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?auto=format&fit=crop&w=800&q=60" },
    price: 1800, location: "Paro", country: "Bhutan",
  },
  {
    title: "Solar-Powered Cabin in Patagonia",
    description: "Explore glacier hikes and condor sightings from this off-grid solar cabin at the edge of the world.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1501594907352-04cda38ebc29?auto=format&fit=crop&w=800&q=60" },
    price: 2200, location: "Torres del Paine", country: "Chile",
  },
  {
    title: "Art Gallery Loft in Berlin",
    description: "Sleep surrounded by rotating contemporary art in this curated loft in Berlin's creative Mitte district.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1560185007-cde436f6a4d0?auto=format&fit=crop&w=800&q=60" },
    price: 1250, location: "Berlin", country: "Germany",
  },
  {
    title: "Geothermal Spa Cottage in Iceland",
    description: "Soak in natural hot springs and watch the Northern Lights from this remote geothermal spa cottage.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1531366936337-7c912a4589a7?auto=format&fit=crop&w=800&q=60" },
    price: 3400, location: "Reykjavik", country: "Iceland",
  },
  {
    title: "Rooftop Apartment in Rome",
    description: "Sip espresso with views of the Colosseum from this stunning rooftop apartment in ancient Rome.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1552832230-c0197dd311b5?auto=format&fit=crop&w=800&q=60" },
    price: 2600, location: "Rome", country: "Italy",
  },
  {
    title: "Surf Shack in Byron Bay",
    description: "Grab your board and head straight to the waves from this laid-back surf shack near Byron Bay's best breaks.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1510414842594-a61c69b5ae57?auto=format&fit=crop&w=800&q=60" },
    price: 1150, location: "Byron Bay", country: "Australia",
  },
  {
    title: "Converted Barn in Vermont",
    description: "Enjoy fall foliage and farm-to-table living in this beautifully converted New England barn.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1440342359743-84fcb8c21f21?auto=format&fit=crop&w=800&q=60" },
    price: 1450, location: "Vermont", country: "United States",
  },
  {
    title: "Lakeside Villa in Bali",
    description: "Enjoy total privacy and tranquility at this serene lakeside villa beside the sacred Bratan Lake.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=800&q=60" },
    price: 1700, location: "Bedugul", country: "Indonesia",
  },
  {
    title: "Hacienda in the Yucatan",
    description: "Swim in a cenote on your doorstep and explore Mayan ruins from this authentic Yucatan hacienda.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1504701954957-2010ec3bcec1?auto=format&fit=crop&w=800&q=60" },
    price: 2300, location: "Mérida", country: "Mexico",
  },
  {
    title: "Traditional Guesthouse in Petra",
    description: "Sleep within walking distance of the rose-red city of Petra in this cozy stone guesthouse.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1517760444937-f6397edcbbcd?auto=format&fit=crop&w=800&q=60" },
    price: 880, location: "Wadi Musa", country: "Jordan",
  },
  {
    title: "Oceanfront Mansion in the Hamptons",
    description: "Entertain in grand style at this sprawling oceanfront estate in the exclusive Hamptons.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=800&q=60" },
    price: 8500, location: "The Hamptons", country: "United States",
  },
  {
    title: "Gypsy Wagon in the Pyrenees",
    description: "Roam the foothills of the Pyrenees or park beside a babbling brook in this beautifully fitted gypsy caravan.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1464278533981-50106e6176b1?auto=format&fit=crop&w=800&q=60" },
    price: 700, location: "Andorra la Vella", country: "Andorra",
  },
  {
    title: "Clifftop Bungalow in Uluwatu",
    description: "Watch epic surf breaks and fire dance shows from this clifftop bungalow above the Indian Ocean.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1552733407-5d5c46c3bb3b?auto=format&fit=crop&w=800&q=60" },
    price: 1300, location: "Uluwatu", country: "Indonesia",
  },
  {
    title: "Minimalist Studio in Copenhagen",
    description: "Live the Danish hygge lifestyle in this beautifully minimalist studio in central Copenhagen.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=800&q=60" },
    price: 1600, location: "Copenhagen", country: "Denmark",
  },
  {
    title: "Ancient Trullo in Puglia",
    description: "Stay in a centuries-old stone trullo in the Valle d'Itria, a UNESCO heritage landscape.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1533587851505-d119e13fa0d7?auto=format&fit=crop&w=800&q=60" },
    price: 1100, location: "Alberobello", country: "Italy",
  },
  {
    title: "Seaside Cottage in Cinque Terre",
    description: "Perch above the rainbow-coloured cliffside villages of Cinque Terre in this quaint sea-view cottage.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1516483638261-f4dbaf036963?auto=format&fit=crop&w=800&q=60" },
    price: 2000, location: "Vernazza", country: "Italy",
  },
  {
    title: "Arctic A-Frame in Norway",
    description: "Watch fjords and waterfalls from the floor-to-ceiling glass walls of this spectacular Norwegian A-frame cabin.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1531366936337-7c912a4589a7?auto=format&fit=crop&w=800&q=60" },
    price: 2850, location: "Flåm", country: "Norway",
  },
  {
    title: "Thatched Villa in Zanzibar",
    description: "Lounge beneath swaying palms at this beachfront thatched villa on the spice island of Zanzibar.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=800&q=60" },
    price: 2100, location: "Stone Town", country: "Tanzania",
  },
  {
    title: "Hillside Retreat in Positano",
    description: "Climb the iconic staircases of Positano to reach this secluded hilltop retreat with panoramic sea views.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1516483638261-f4dbaf036963?auto=format&fit=crop&w=800&q=60" },
    price: 3100, location: "Positano", country: "Italy",
  },
  {
    title: "Lakefront Cabin in Minnesota",
    description: "Cast your line and canoe at sunrise from this classic Northwoods cabin on a pristine Minnesota lake.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?auto=format&fit=crop&w=800&q=60" },
    price: 950, location: "Boundary Waters", country: "United States",
  },
  {
    title: "Cliffside Eco-Lodge in Peru",
    description: "Stand at the edge of the Sacred Valley in this daring eco-lodge cantilevered over a Peruvian canyon.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1501594907352-04cda38ebc29?auto=format&fit=crop&w=800&q=60" },
    price: 2700, location: "Sacred Valley", country: "Peru",
  },
  {
    title: "Countryside Inn in the Cotswolds",
    description: "Wander honeyed stone villages and pub-dotted lanes from this classic English countryside inn.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1468824357306-a439d58ccb1c?auto=format&fit=crop&w=800&q=60" },
    price: 1350, location: "Bourton-on-the-Water", country: "United Kingdom",
  },
  {
    title: "Volcanic Retreat in Hawaii",
    description: "Witness glowing lava flows and snorkel with sea turtles from this dramatic retreat on the Big Island.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=60" },
    price: 2400, location: "Kona", country: "United States",
  },
  {
    title: "Eco Dome in the Namib Desert",
    description: "Sleep under starry African skies inside a transparent dome set amid the world's oldest desert.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1509316785289-025f5b846b35?auto=format&fit=crop&w=800&q=60" },
    price: 3000, location: "Sossusvlei", country: "Namibia",
  },
  {
    title: "Boutique Riad in Fez",
    description: "Lose yourself in the ancient medina of Fez and return to this beautifully tiled boutique riad.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1560185893-a55cbc8c57e8?auto=format&fit=crop&w=800&q=60" },
    price: 1150, location: "Fez", country: "Morocco",
  },
  {
    title: "Private Beach Villa in Seychelles",
    description: "Your own slice of paradise — this private villa comes with a butler, chef, and pristine private beach.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=800&q=60" },
    price: 9000, location: "Mahé", country: "Seychelles",
  },
];

module.exports = { data: sampleListings };